name: Hello World Docker Chceker

on: 
  push:
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: github/checkout@v4

      - id: hello-world
        uses: ./hello-world-docker-action
        with:
          whom-to-wish: 
    
