name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * SUN' 

  workflow_dispatch:

jobs:    
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Trigger
        run: echo "The event that triggered this event was ${{github.event_name}}"

      - name: Output Repo
        run: echo "The repository is ${{ github.repository }}"

      - uses: actions/checkout@v4
      - run: |
          echo "Thes are the files in the repository: "
          tree
          

    
